### ISSUE TITLE
Identify included surveys

### ISSUE THREAD

**Issue by samsoe** [samsoe/mpg_surveys#2]
- bird_point_count_summaries.abundance_order
- vegetation_biomass.horizontal_cover_robel

**Comment by samsoe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Discuss and launch survey map project](https://trello.com/c/Gcddx69l/232-discuss-and-launch-survey-map-project)

**Comment by bglarkin** [comment]
**Surveys to include**
This is a simple list of the surveys that we need to show. This will help find the correct resources in BQ.
- Vegetation, point intercept cover
- Vegetation, quadrat cover
- Vegetation, biomass
- Vegetation, visual obstruction rating (i.e., Robel pole)
- Mammalian herbivores, pellet counts
- Birds, point count data

It's worth checking out how we could include bees. I'm not sure how grid point specific the observations of bees are. @samsoe what do you think? I know you've worked with the bee data a bit.

**Comment by bglarkin** [comment]
**Names**
@samsoe let's use better names for these resources on the map application. See attached file. 

[survey names.csv](https://github.com/samsoe/mpg_surveys/files/6625649/survey.names.csv)

**Comment by samsoe** [comment]
542K for LIMIT 10000
1.5M for full 28000

**Comment by samsoe** [comment]
@bglarkin about the bees.... the bee database dump I got has lat long. I don't see a grid point reference.
